In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /home/remy/.pyenv/versions/3.10.6/envs/mammo-analysis/lib/python3.10/site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /home/remy/.pyenv/versions/3.10.6/envs/mammo-analysis/lib/python3.10/site-packages (from openpyxl) (1.1.0)

In [2]:
import os
import pandas as pd
import numpy as np
from PIL import Image

In [3]:
PROJECT_DIR = os.path.dirname(os.getcwd())
DATA_DIR = os.path.join(PROJECT_DIR, 'data')
METADATA_PATH = os.path.join(DATA_DIR, 'metadata')
IMG_PATH = os.path.join(DATA_DIR, 'images')

In [4]:
csv_path = os.path.join(METADATA_PATH, 'kaggle.xlsx')
metadata = pd.read_excel(csv_path)
metadata

,site_id,patient_id,image_id,laterality,view,age,cancer,biopsy,invasive,BIRADS,implant,density,machine_id,difficult_negative_case
0,2,10006,462822612,L,CC,61.0,0,0,0,NaN,0,NaN,29,False
1,2,10006,1459541791,L,MLO,61.0,0,0,0,NaN,0,NaN,29,False
2,2,10006,1864590858,R,MLO,61.0,0,0,0,NaN,0,NaN,29,False
3,2,10006,1874946579,R,CC,61.0,0,0,0,NaN,0,NaN,29,False
4,2,10011,220375232,L,CC,55.0,0,0,0,0.0,0,NaN,21,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54701,1,9973,1729524723,R,MLO,43.0,0,0,0,1.0,0,C,49,False
54702,1,9989,63473691,L,MLO,60.0,0,0,0,NaN,0,C,216,False
54703,1,9989,1078943060,L,CC,60.0,0,0,0,NaN,0,C,216,False
54704,1,9989,398038886,R,MLO,60.0,0,0,0,0.0,0,C,216,True
54705,1,9989,439796429,R,CC,60.0,0,0,0,0.0,0,C,216,True

In [5]:
images_path = os.path.join(IMG_PATH, 'data_processed')
ids = []
for file_name in os.listdir(images_path):
    # print(os.path.join(images_path, file_name))
    id = os.path.splitext(file_name)[0]
    ids.append(id)

In [6]:
img = os.listdir(images_path)[10]
image = os.path.join(images_path, img)

In [7]:
clean_data_dict = {}
for img in os.listdir(images_path)[:200]:
    if ".jpg" in img:
        image = os.path.join(images_path, img)
        clean_data_dict[img.replace('.jpg', '')] = np.array(Image.open(image))
    else:
        continue
clean_data_df = pd.DataFrame(clean_data_dict.items(), columns=['image_id', 'np_array_img'])

In [8]:
final_sample = clean_data_df.combine_first(metadata[['image_id', 'cancer']])
final_sample_train = pd.DataFrame(final_sample.head(200))

In [9]:
final_sample_train

     cancer    image_id                                       np_array_img
0         0  1834201085  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
1         0   227919373  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
2         0  2048218442  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
3         0  1808945924  [[255, 255, 255, 255, 255, 255, 255, 255, 255,...
4         0  1458259706  [[255, 255, 255, 255, 255, 255, 255, 255, 255,...
..      ...         ...                                                ...
195       0   769115829  [[171, 142, 106, 91, 71, 60, 48, 0, 0, 0, 0, 0...
196       0  1944703225  [[23, 22, 21, 21, 22, 24, 26, 27, 25, 24, 22, ...
197       0   528611413  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
198       0  1658150385  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
199       0  1726562879  [[205, 197, 193, 197, 201, 201, 199, 200, 203,...

[200 rows x 3 columns]

In [10]:
y_train = final_sample_train['cancer']
X_train = final_sample_train['np_array_img']